### ISSUE TITLE
library breaks fabric context managers

### ISSUE THREAD

**Issue by jberryman** [JasperVanDenBosch/fexpect#8]
And I have to assume a lot of other things.

fab file:

```
from ilogue.fexpect import expect, expecting, run

@task
def crap():
    with cd('/tmp'):
        run('touch test')
```

error:

```
» fab -H ubuntu@x crap                                                                                                                                     
[ubuntu@x] Executing task 'crap'
Traceback (most recent call last):
  File "/x/mgmt/local/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/x/mgmt/local/lib/python2.7/site-packages/fabric/tasks.py", line 299, in execute
    multiprocessing
  File "/x/mgmt/local/lib/python2.7/site-packages/fabric/tasks.py", line 198, in _execute
    return task.run(*args, **kwargs)
  File "/x/mgmt/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/x/mgmt/fabfile.py", line 1017, in crap
    run('touch test')
  File "/x/mgmt/local/lib/python2.7/site-packages/ilogue/fexpect/api.py", line 15, in run
    wrappedCmd = wrapExpectations(cmd)
  File "x/mgmt/local/lib/python2.7/site-packages/ilogue/fexpect/internals.py", line 15, in         wrapExpectations
    script = createScript(cmd)
  File "/x/mgmt/local/lib/python2.7/site-packages/ilogue/fexpect/internals.py", line 39, in createScript
    for e in fabric.state.env.expectations:
  File "/x/mgmt/local/lib/python2.7/site-packages/fabric/utils.py", line 168, in __getattr__
    raise AttributeError(key)
AttributeError: expectations
```

**Comment by JasperVanDenBosch** [comment]
This should be fixed by Jim's patch (#11)
